[workspace]
members = ["kora_pool", "kora_business", "kora_credit"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
mpl-bubblegum = { version = "2.1.1", default-features = false }
solana-program = "=1.18.26"

[profile.release]
overflow-checks = true

[profile.release.build-override]
overflow-checks = true
